
//events we will emit using socket
module.exports = {
  COMMUNITY_CHAT: "OMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT"
};
